name: ctplot
channels:
  - defaults
dependencies:
  - python=2 
  - numpy 
  - scipy 
  - pandas
  - matplotlib=2.0.2 
  - basemap
  - basemap-data-hires
  - pytz 
  - numexpr 
  - pytables 
  - python-dateutil 
  - Pillow 
  - locket
